name: Testing Apidog Collection
on: [push]
jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4


      # INstall Node on the runner
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"


      # Install the apidog command line utility
      - name: Install Apidog CLI
        run: |
          npm install -g apidog-cli
