name: Testing Apidog Collection
on: [push]
jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4


      # INstall Node on the runner
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      # Caching the NODE and Apidog CLI
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-global-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-global-

      # Install the apidog command line utility
      - name: Install Apidog CLI
        run: |
          npm install -g apidog-cli

      # Caching the NODE and Apidog CLI
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-global-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-global-          

      # Run the apidog CLI collection
      - name: Run the apidog CLI collection
        run: |
          apidog run .github/API-Test-SC-01.apidog-cli.json --insecure
